# Generated by Django 4.2.29 on 2026-03-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Enquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("interest", models.CharField(max_length=100)),
                ("budget", models.CharField(max_length=100)),
                ("message", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name_plural": "Enquiries",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=300)),
                ("price", models.CharField(max_length=100)),
                (
                    "listing_type",
                    models.CharField(
                        choices=[("sale", "For Sale"), ("rent", "For Rent")],
                        default="sale",
                        max_length=10,
                    ),
                ),
                ("tag", models.CharField(default="For Sale", max_length=50)),
                (
                    "tag_class",
                    models.CharField(
                        choices=[
                            ("badge-sale", "For Sale"),
                            ("badge-rent", "For Rent"),
                            ("badge-new", "New Launch"),
                        ],
                        default="badge-sale",
                        max_length=20,
                    ),
                ),
                ("beds", models.CharField(default="3", max_length=10)),
                ("baths", models.CharField(default="2", max_length=10)),
                ("area", models.CharField(max_length=50)),
                ("floor", models.CharField(max_length=50)),
                ("contact", models.CharField(max_length=20)),
                ("agent", models.CharField(max_length=100)),
                ("image_url", models.URLField(blank=True, default="", max_length=500)),
                ("description", models.TextField()),
                ("is_featured", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Properties",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("role", models.CharField(max_length=150)),
                ("text", models.TextField()),
                ("avatar_url", models.URLField(blank=True, max_length=500)),
                ("rating", models.IntegerField(default=5)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
