# Generated by Django 4.2.29 on 2026-03-21 11:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="testimonial",
            options={
                "ordering": ["order", "-submitted_at"],
                "verbose_name_plural": "Testimonials",
            },
        ),
        migrations.AddField(
            model_name="testimonial",
            name="is_user_submitted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Review"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="submitted_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="is_active",
            field=models.BooleanField(
                default=False,
                help_text="Approved testimonials only appear on site when this is checked.",
            ),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="order",
            field=models.IntegerField(
                default=0, help_text="Lower number = appears first"
            ),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="role",
            field=models.CharField(
                help_text="E.g. Homeowner, Vasant Kunj  or  Investor, Gurugram",
                max_length=150,
            ),
        ),
    ]
